version: "latest"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  python:
    image: python:3.11.7
    restart: no
    volumes:
      - .:/app  # Monta todo el directorio actual en /app dentro del contenedor
    command: bash -c "pip install -r /app/requirements.txt && python /app/main.py"

volumes:
  postgres:

